default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('PG_HOST', 'localhost') %>
  database: chicken_dev_june
  username: <%= ENV.fetch('PG_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('PG_PASSWORD', 'p@ssw0rd') %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: chicken_test_june

production:
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['CHICKEN_DB_HOST'] %>
  pool: 5
  username: <%= ENV['CHICKEN_DB_USERNAME'] %>
  password: <%= ENV['CHICKEN_DB_PASSWORD'] %>
  database: <%= ENV['CHICKEN_DB_DATABASE'] %>
  timeout: 5000
